---
title: "06_DifferentialAbundance"
author: "Callum Hudson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#BiocManager::install("ANCOMBC")
library(ANCOMBC)
library(writexl)
library(ggtext)

sapply(c("ANCOMBC","tidyverse"), 
        require, character.only = TRUE)
```

```{r}
level_order1 <- c('Reference', 'Elevated CO2')

tissue_daa <- ps_gut_clean

sample_data(tissue_daa)$Site <- factor(sample_data(tissue_daa)$Condition, levels = level_order1)

table(sample_data(tissue_daa)$Site)
summary(tissue_daa)
```


```{r}
# ANCOMBC - New Way # KEEP THIS!
library(viridis)

output_daa_tissue_new = ancombc2(data = tissue_daa, assay_name = "counts", tax_level = "Genus",
                  fix_formula = "Site", rand_formula = NULL,
                  p_adj_method = "fdr", pseudo = 0, pseudo_sens = TRUE,
                  prv_cut = 0.01, lib_cut = 0, s0_perc = 0.05,
                  group = "Site", struc_zero = TRUE, neg_lb = FALSE,
                  alpha = 0.05, n_cl = 2, verbose = TRUE,
                  global = TRUE, pairwise = FALSE, dunnet = TRUE, trend = TRUE,
                  iter_control = list(tol = 1e-2, max_iter = 20, 
                                      verbose = TRUE),
                  em_control = list(tol = 1e-5, max_iter = 100),
                  lme_control = lme4::lmerControl(),
                  mdfdr_control = list(fwer_ctrl_method = "fdr", B = 100),
                  trend_control = list(contrast = list(matrix(c(1, 0, -1, 1),
                                                              nrow = 2, 
                                                              byrow = TRUE),
                                                       matrix(c(-1, 0, 1, -1),
                                                              nrow = 2, 
                                                              byrow = TRUE)),
                                       node = list(2, 2),
                                       solver = "ECOS",
                                       B = 100))

# These parameters are less conservative, better for exploratory analyses. 
# alpha (p-cutoff) set at 0.05 rather than 0.001 etc.

# ANCOMBC Bar Plot - All of these are significantly differentially expressed (p < 0.05)

res_prim = output_daa_tissue_new$res
res_prim
df_res = res_prim %>% dplyr::filter(`diff_SiteElevated CO2`) %>%
    dplyr::select(taxon, contains("SiteElevated CO2")) 
# 45 taxa differentially expression (p < 0.05)

View(df_res)

# Arrange in order of lfc
df_fig_res = df_res %>% 
    arrange(desc(`lfc_SiteElevated CO2`
)) %>%
    mutate(direct = ifelse(`lfc_SiteElevated CO2`
 > 0, "Positive LFC", "Negative LFC"))

df_fig_res$taxon = factor(df_fig_res$taxon, levels = df_fig_res$taxon)
df_fig_res$direct = factor(df_fig_res$direct, 
                           levels = c("Positive LFC", "Negative LFC"))

# Set color bounds
lo_val <- floor(min(df_fig_res$`lfc_SiteElevated CO2`))
up_val <- ceiling(max(df_fig_res$`lfc_SiteElevated CO2`))
mid_val <- (lo_val + up_val) / 2

fig_res = df_fig_res %>%
    ggplot(aes(x = taxon, y = `lfc_SiteElevated CO2`, fill = `lfc_SiteElevated CO2`)) + 
    geom_bar(stat = "identity", width = 0.7, color = "black", 
             position = position_dodge(width = 0.4)) +
    geom_errorbar(aes(ymin = `lfc_SiteElevated CO2` - `se_SiteElevated CO2`, ymax = `lfc_SiteElevated CO2` + `se_SiteElevated CO2`), 
                  width = 0.2, position = position_dodge(0.05), color = "black") + 
    labs(x = "Genus", y = "Log fold change") + scale_fill_viridis_c(option = "plasma") + scale_color_viridis_c(option = "plasma") +
  theme_bw() + 
  theme(legend.position = "none",
        panel.grid.minor.y = element_blank()) + coord_flip()

fig_res

# Trying with site colors
fig_res = df_fig_res %>%
    ggplot(aes(x = taxon, y = `lfc_SiteElevated CO2`, fill = `lfc_SiteElevated CO2`)) + 
    geom_bar(stat = "identity", width = 0.7, color = "black", 
             position = position_dodge(width = 0.4)) +
    geom_errorbar(aes(ymin = `lfc_SiteElevated CO2` - `se_SiteElevated CO2`, ymax = `lfc_SiteElevated CO2` + `se_SiteElevated CO2`), 
                  width = 0.2, position = position_dodge(0.05), color = "black") + 
    labs(x = "Genus", y = "Log fold change") + scale_fill_gradient2(
    low = "#2C728E", high = "#D4476C", mid = "white", 
    na.value = "white", midpoint = mid_val, 
    limit = c(lo_val, up_val), name = NULL
  ) +
  theme_bw() + 
  theme(legend.position = "none",
        panel.grid.minor.y = element_blank()) + coord_flip()

fig_res

ggsave('Figures_Alpha_Beta_div/daa_fig_tissue_lfc_se.svg', width = 20, height = 20, units = 'cm', dpi = 900)

```
# Final plot
```{r}
df_fig_res <- df_fig_res %>%
  mutate(
    direction = ifelse(`lfc_SiteElevated CO2` > 0,
                       "Elevated CO2",
                       "Reference"),
    neglog10_p = -log10(`p_SiteElevated CO2`)
  )

fig_res <- ggplot(
  df_fig_res,
  aes(
    x = taxon,
    y = `lfc_SiteElevated CO2`,
    fill = direction,
    alpha = neglog10_p
  )
) +
  geom_col(width = 0.7, colour = "black") +
  geom_errorbar(
  data = df_fig_res,
  inherit.aes = FALSE,
  aes(
    x = taxon,
    ymin = `lfc_SiteElevated CO2` - `se_SiteElevated CO2`,
    ymax = `lfc_SiteElevated CO2` + `se_SiteElevated CO2`
  ),
  colour = "black",
  width = 0.2
) +
  coord_flip() +
  scale_fill_manual(
    values = c(
      "Reference" = "#2C728E",
      "Elevated CO2" = "#D4476C"
    ),
    guide = "none"
  ) +
  scale_alpha_continuous(
    range = c(0.3, 1),
    name = expression(-log[10]~"adjusted p-value")
  ) +
  labs(
    x = "Genus",
    y = "Log fold change"
  ) +
  theme_bw() +
  theme(
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank()
)

fig_res

ggsave('Figures_Alpha_Beta_div/daa_fig_tissue_lfc_se.svg', width = 20, height = 20, units = 'cm', dpi = 900)
```


